### ISSUE TITLE
Non-reactive chat memory crashes response streaming

### ISSUE THREAD

**Issue by florian-h05** [quarkiverse/quarkus-langchain4j#1120] opened 2024-11-29 15:24 UTC
When using response streaming in a REST resource, I always receive the following exception when using `quarkus-langchain4j-memory-store-redis`:

```
java.lang.IllegalStateException: The current thread cannot be blocked: vert.x-eventloop-thread-9
        at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:30)
        at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
        at io.quarkus.redis.runtime.datasource.BlockingStringCommandsImpl.get(BlockingStringCommandsImpl.java:41)
        at io.quarkiverse.langchain4j.memorystore.RedisChatMemoryStore.getMessages(RedisChatMemoryStore.java:33)
        at io.quarkiverse.langchain4j.memorystore.RedisChatMemoryStore_xTEUBJ9I9t7XqF0naKuYsMHw80A_Synthetic_ClientProxy.getMessages(Unknown Source)
        at dev.langchain4j.memory.chat.MessageWindowChatMemory.messages(MessageWindowChatMemory.java:84)
        at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.doImplement(AiServiceMethodImplementationSupport.java:150)
        at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.implement(AiServiceMethodImplementationSupport.java:131)
        ...
```

Full reproducal project can be found at https://github.com/florian-h05/quarkus-langchain4j-1120.

How can I fix that? Is there a way to have a reactive chat memory store?

I am using Quarkus 3.17.0 with Quarkus LangChain4j 0.22.0.

**Comment by florian-h05** [comment] 2024-12-02 07:44
IIRC Quarkus has a reactive Redis client, but I have no idea how to use that and keep it compatible with LangChain4j‘s ChatMemorxStore interface at the same time.

BTW the same issue as with the chat memory store also occurs when using a RetrievalAugmentor because the embedding store is queried blocking.

**Comment by dennysfredericci** [comment] 2024-12-02 07:57
Ah, yes, that's a good one. I encountered the same issue last week and, to work around it, did not use reactive in the `RegisterAiService`.

Switching to a worker thread for handling memory operations seems a good approach.

**Comment by geoand** [comment] 2024-12-02 08:42
@florian-h05 can you attach a small sample I can use to test various ideas against?

**Comment by florian-h05** [comment] 2024-12-02 09:27
I have updated my first message with a ChatMemoryProvider bean. 
Reading https://docs.quarkiverse.io/quarkus-langchain4j/dev/ai-services.html#memory, the registered AI service should automatically make use of this. You need to add the `quarkus-langchain4j-memory-store-redis` plugin installed.

Is that enough or should I spinup a small sample project repo?

BTW, I am in fact not using `@RegisterAiService` in production (but have verified the issue exists with this as well), instead I create my AiServices through the AiService.builder() as I need to have different implementations of my AiService with different chat language models configurable during runtime.

**Comment by geoand** [comment] 2024-12-02 09:48
> Is that enough or should I spinup a small sample project repo?

Please, do.

Thanks

**Comment by florian-h05** [comment] 2024-12-02 12:58
@geoand I have a minimal sample project to reproduce the issue: https://github.com/florian-h05/quarkus-langchain4j-1120

**Comment by geoand** [comment] 2024-12-02 13:01
🙏🏽

**Comment by geoand** [comment] 2024-12-02 13:20
I'll have a closer look tomorrow but for the time being any solution we come with won't be pretty

**Comment by geoand** [comment] 2024-12-02 14:15
The simplest way around it for the time being is to add `@Blocking` on `RestResource`

**Comment by geoand** [comment] 2024-12-02 14:49
It works just fine in this simpliefied scenario:

```diff
diff --git a/src/main/java/com/florianhotze/quarkus/langchain4j/Assistant.java b/src/main/java/com/florianhotze/quarkus/langchain4j/Assistant.java
index c2b81ef..93dd8c9 100644
--- a/src/main/java/com/florianhotze/quarkus/langchain4j/Assistant.java
+++ b/src/main/java/com/florianhotze/quarkus/langchain4j/Assistant.java
@@ -1,13 +1,10 @@
 package com.florianhotze.quarkus.langchain4j;
 
-import dev.langchain4j.service.MemoryId;
-import dev.langchain4j.service.TokenStream;
 import dev.langchain4j.service.UserMessage;
 import io.quarkiverse.langchain4j.RegisterAiService;
+import io.smallrye.mutiny.Multi;
 
 @RegisterAiService
 public interface Assistant {
-    TokenStream chat(@UserMessage String prompt);
-
-    TokenStream chat(@MemoryId Object memoryId, @UserMessage String prompt);
+    Multi<String> chat(@UserMessage String prompt);
 }
diff --git a/src/main/java/com/florianhotze/quarkus/langchain4j/RestResource.java b/src/main/java/com/florianhotze/quarkus/langchain4j/RestResource.java
index 2dc030e..e9a355b 100644
--- a/src/main/java/com/florianhotze/quarkus/langchain4j/RestResource.java
+++ b/src/main/java/com/florianhotze/quarkus/langchain4j/RestResource.java
@@ -1,5 +1,6 @@
 package com.florianhotze.quarkus.langchain4j;
 
+import io.smallrye.common.annotation.Blocking;
 import io.smallrye.mutiny.Multi;
 import jakarta.inject.Inject;
 import jakarta.ws.rs.Consumes;
@@ -37,18 +38,8 @@ class RestResource {
             @Content(
                     mediaType = MediaType.SERVER_SENT_EVENTS,
                     schema = @Schema(implementation = String.class)))
+    @Blocking
     public Multi<String> streamingPrompt(String prompt) {
-        Multi<String> sourceMulti =
-                Multi.createFrom()
-                        .emitter(
-                                emitter ->
-                                        assistant
-                                                .chat(prompt)
-                                                .onNext(emitter::emit)
-                                                .onError(emitter::fail)
-                                                .onComplete(response -> emitter.complete())
-                                                .start());
-
-        return RestMulti.fromMultiData(sourceMulti).withDemand(1).status(200).build();
+        return RestMulti.fromMultiData(assistant.chat(prompt)).withDemand(1).status(200).build();
     }
 }
diff --git a/src/main/resources/application.properties b/src/main/resources/application.properties
index 85ce614..633366c 100644
--- a/src/main/resources/application.properties
+++ b/src/main/resources/application.properties
@@ -1,2 +1,2 @@
-quarkus.langchain4j.memorystore.redis.client-name=chat-memory
-quarkus.redis.chat-memory.hosts=redis://localhost:6379/0
+#quarkus.langchain4j.memorystore.redis.client-name=chat-memory
+#quarkus.redis.chat-memory.hosts=redis://localhost:6379/0
```

**Comment by cescoffier** [comment] 2024-12-02 16:27
I think it's because you added the `@Blocking`.

**Comment by florian-h05** [comment] 2024-12-02 17:33
> It works just fine in this simpliefied scenario:

I have applied your diff in the reproduce repo, for me it did not fix the issue. I don't understand why not. 
I jave just invited you to the reproduce repo, can you please push your changes to a new branch there?

**Comment by florian-h05** [comment] 2024-12-04 15:11
Thanks for pushing your changes.
Just tried this on a different machine, still doesn't work for me.

**Comment by dennysfredericci** [comment] 2024-12-04 20:56
> The simplest way around it for the time being is to add `@Blocking` on `RestResource`

Just another confirmation like @florian-h05  I also did it and it failed... For m,e it fails when I get an answer from the model and quarkus-langchain4j tries to update the memory.

**Comment by geoand** [comment] 2024-12-05 07:28
Ah okay, tried it again and I do indeed see an the thread being blocked.

@cescoffier this seems to have to do with the `TokenStreamMulti` handling. 

I added some breakpoints to the reproducer and I see:

```
Breakpoint reached at com.florianhotze.quarkus.langchain4j.RestResource.streamingPrompt(RestResource.java:43)
executor-thread-1
Breakpoint reached at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.doImplement(AiServiceMethodImplementationSupport.java:269)
executor-thread-1
Breakpoint reached at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport$TokenStreamMulti.createTokenStream(AiServiceMethodImplementationSupport.java:814)
vert.x-eventloop-thread-2
```

**Comment by cescoffier** [comment] 2024-12-05 07:31
I will have a look when I'm back. I'm wondering why the multi starts emitting on the event loop. I may have missed a 'capture and switch context'

**Comment by cescoffier** [comment] 2024-12-09 17:44
Please look at my PR - it fixes the issue (when the method still need to be marked as blocking)

**Comment by dennysfredericci** [comment] 2024-12-11 20:52
@cescoffier I built a version of quarkus-langchain4j from your branch and integrated it into my project. However, I am still encountering the same exception:

```
java.lang.IllegalStateException: The current thread cannot be blocked: vert.x-eventloop-thread-3
        at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:30)
        at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
        at io.quarkus.redis.runtime.datasource.BlockingStringCommandsImpl.get(BlockingStringCommandsImpl.java:41)
        at br.com.fredericci.memory.CustomChatInMemoryStore.getMessages(CustomChatInMemoryStore.java:32)
        at br.com.fredericci.memory.CustomChatInMemoryStore_ClientProxy.getMessages(Unknown Source)
        at dev.langchain4j.memory.chat.MessageWindowChatMemory.messages(MessageWindowChatMemory.java:84)
        at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.doImplement(AiServiceMethodImplementationSupport.java:151)
        at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.implement(AiServiceMethodImplementationSupport.java:131)
        at br.com.fredericci.ChatBotAssistant$$QuarkusImpl.getAnswer(Unknown Source)
        at br.com.fredericci.ChatBotAssistant$$QuarkusImpl_ClientProxy.getAnswer(Unknown Source)
```


The issue seems to be linked with ```context.chatMemory(memoryId).messages()``` which relies on blocking operation as you can see in the stacktrace.

**Comment by cescoffier** [comment] 2024-12-12 05:49
Does your method still have the @Blocking annotations?

**Comment by dennysfredericci** [comment] 2024-12-12 09:36
Do you mean the web socket method? It doesn't have it. Should I add @Blocking it?

**Comment by dennysfredericci** [comment] 2024-12-12 09:41
Ah, ok I see it now... I included the @Blocking annotation and it is working fine now.

![Screenshot 2024-12-12 at 10 40 49](https://github.com/user-attachments/assets/b331850f-74f7-465c-b241-bc3994b6501e)

Thanks for your feedback.

**Closed** 2024-12-13 07:41 UTC
Labels: bug

**Comment by florian-h05** [comment] 2024-12-13 07:48
@cescoffier Many thanks for fixing this annoying issue!
