### ISSUE TITLE
Preloading ollama model should only happen if the model doesn't already exist

### ISSUE THREAD

**Issue by edeandrea** [quarkiverse/quarkus-langchain4j#647] opened 2024-05-31 18:28 UTC
When preloading an Ollama model, it should first check to see whether or not the model already exists.

For example, if I'm using the mixtral model, it takes almost 10 minutes to download/install. Isn't there an API call to detect whether the model is already present?

Maybe additional logic in

https://github.com/quarkiverse/quarkus-langchain4j/blob/ccb3ce251d794cb0d781d6aed9adaec38db26c6e/core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/devservice/JdkOllamaClient.java#L127-L152

Also, why is Ollama-specific stuff inside the `core` deployment module? Shouldn't it belong in the ollama extension?

**Comment by geoand** [comment] 2024-05-31 18:35
> Isn't there an API call to detect whether the model is already present?

We already do that, so I'm interested in how you reproduce what you mention

**Comment by edeandrea** [comment] 2024-05-31 18:41
If I already have the model present

```bash
╰─ ollama ls
NAME                    ID              SIZE    MODIFIED       
nomic-embed-text:latest 0a109f422b47    274 MB  39 minutes ago  
mixtral:latest          d39eb76ed9c5    26 GB   39 minutes ago  
```

When I run `quarkus dev` I see

```
Ollama model pull: 2024-05-31 14:39:40,154 INFO  [io.qua.lan.dep.dev.DevServicesOllamaProcessor] (build-59) Preloading model mixtral
```

And it sits there for about 15 minutes.

There isn't any code which reaches out to see if the model is already present. It's instructing ollama to re-pull the model.

https://github.com/quarkiverse/quarkus-langchain4j/blob/ccb3ce251d794cb0d781d6aed9adaec38db26c6e/core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/devservice/DevServicesOllamaProcessor.java#L144-L148

If I also add `-Dquarkus.langchain4j.devservices.preload=false`, it skips that step and immediately starts and my app works fine, because the model is already loaded.

**Comment by geoand** [comment] 2024-05-31 18:49
That sounds like an Ollama bug TBH.

**Comment by geoand** [comment] 2024-06-03 05:52
I tried this and preloading a model works exactly as expected, I could not reproduce the behavior you are seeing.

**Comment by geoand** [comment] 2024-06-04 06:49
Closing as I cannot reproduce. 

Feel free to add more information and I can have another look.

**Closed by geoand** 2024-06-04 06:49 UTC
Labels: bug

**Comment by edeandrea** [comment] 2024-06-05 12:31
Sorry I've been at a f2f this week. I'll be back in the office tomorrow.
