### ISSUE TITLE
Manage properties for multiple @RegisterAiService

### ISSUE THREAD

**Issue by andreadimaio** [quarkiverse/quarkus-langchain4j#210] opened 2024-01-08 09:29 UTC
Today, if you have multiple `@RegisterAiService` in a project, where each of them needs different properties (like mode-id or others...), the only way to specialize them is to use the `chatMemoryProviderSupplier` property, one for each `@RegisterAiService`.

It may be useful to do this through the use of `application.properties`.
For more information (context and example), there is a post in [Zulip](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/.E2.9C.94.20quarkus-langchain.3A.20How.20to.20manage.20multiple.20.40RegisterAiSe.2E.2E.2E/near/411491790).

**Comment by geoand** [comment] 2024-01-08 09:32
Thanks for the reporting!

@edeandrea did you have a similar use case, or what it a little different?

**Comment by edeandrea** [comment] 2024-01-08 13:13
I'm not sure what details are being referred to on Zulip. That link in the original post seems to be broken.

My use case (#56) was not multiple `@RegisterAiService` in a project. My use case is a single `@RegisterAiService` that can be satisfied by multiple extensions (openai & azure-open-ai).

**Comment by geoand** [comment] 2024-01-08 13:16
> That link in the original post seems to be broken.

Oops, fixed now

**Comment by geoand** [comment] 2024-01-08 13:17
> My use case is a single @RegisterAiService that can be satisfied by multiple extensions (openai & azure-open-ai).

Gotcha, thanks for clarifying

**Comment by edeandrea** [comment] 2024-01-08 14:06
Maybe, kinda like datasources, you have the idea of "named" services. And then in the configuration you can have both global config, as well as config that is scoped to a particular named service.

**Comment by geoand** [comment] 2024-01-08 14:17
Yeah, that's probably where we will end up when we do this

**Comment by maxandersen** [comment] 2024-01-09 11:57
yeah, named services was what I was thinking too.

**Comment by geoand** [comment] 2024-01-19 15:32
@cescoffier were discussing this in another context, so I'll probably look into it soon

**Comment by geoand** [comment] 2024-01-29 15:04
This keeps coming up, so I'll likely take it up this week

**Comment by geoand** [comment] 2024-01-30 07:26
This is also related to https://github.com/quarkiverse/quarkus-langchain4j/issues/56

**Comment by geoand** [comment] 2024-01-30 15:07
@cescoffier has an extensive proposal [here](https://github.com/quarkiverse/quarkus-langchain4j/discussions/246).

**Comment by geoand** [comment] 2024-02-15 08:54
@andreadimaio can you try version `0.8.0` and see if there is anything missing now?

**Comment by andreadimaio** [comment] 2024-02-15 09:55
> @andreadimaio can you try version `0.8.0` and see if there is anything missing now?

I plan to try these new changes tomorrow, I'll get back with feedback. 😁

**Comment by andreadimaio** [comment] 2024-02-16 08:50
It seems that there is a problem using the `modelName` in the `@RegisterAiService` annotation.
I'm testing it with the BAM and OpenAI modules for now, and the problem is present with both (version 0.8.1)

If I create a `LLMService` interface like:
```
@RegisterAiService(modelName = "tokenizer")
@SystemMessage("""
    ...
""")
public interface LLMService {

    @UserMessage("""
       ...    
    """)
    public String tokenize(String v);
}
```

with `application.properties`
```
...
quarkus.langchain4j.bam.tokenizer.api-key=...
...
```

When I start Quarkus, I see the error:
```
The config property quarkus.langchain4j.bam.api-key is required but it could not be found in any config source
```

To solve the problem, I need to add both lines to the `application.properties` file
```
quarkus.langchain4j.bam.tokenizer.api-key=...
quarkus.langchain4j.bam.api-key=...
```

**Comment by geoand** [comment] 2024-02-16 08:53
Any chance you can upload the sample you are using so I can try it out?

**Comment by andreadimaio** [comment] 2024-02-16 09:04
> Any chance you can upload the sample you are using so I can try it out?

`git clone https://github.com/andreadimaio/langchain4jquarkustest.git`

**Comment by geoand** [comment] 2024-02-16 09:05
🙏🏼

**Comment by geoand** [comment] 2024-02-16 09:11
I see what the problem is, it's related to DevUI...

**Comment by andreadimaio** [comment] 2024-02-16 09:15
I tried to help you find the problem, but you were too quick. I'll stop my investigations. 😁

**Comment by geoand** [comment] 2024-02-16 09:20
Thanks :)

**Comment by geoand** [comment] 2024-02-16 09:29
https://github.com/quarkiverse/quarkus-langchain4j/pull/309 fixes the problem

**Comment by andreadimaio** [comment] 2024-02-16 14:11
I tested the fix by compiling the code on my workstation using the `999-SNAPSHOT` version and everything works fine.
I did two different tests, in the first one I used the `bam` with two different models, using the `application.properties` like this:

```
quarkus.langchain4j.bam.tokenizer.api-key=${BAM_API_KEY}
quarkus.langchain4j.bam.tokenizer.chat-model.model-id=meta-llama/llama-2-70b-chat

quarkus.langchain4j.bam.tokenizer2.api-key=${BAM_API_KEY}
quarkus.langchain4j.bam.tokenizer2.chat-model.model-id=google/flan-t5-xl
```

And in the second test I have used two different maven modules (`bam`, `watsonx`)

```
quarkus.langchain4j.tokenizer.chat-model.provider=bam
quarkus.langchain4j.bam.tokenizer.api-key=${BAM_API_KEY}
quarkus.langchain4j.bam.tokenizer.chat-model.model-id=meta-llama/llama-2-70b-chat

quarkus.langchain4j.tokenizer2.chat-model.provider=watsonx
quarkus.langchain4j.watsonx.tokenizer2.base-url=https://us-south.ml.cloud.ibm.com
quarkus.langchain4j.watsonx.tokenizer2.project-id=${WATSONX_PROJECT_ID}
quarkus.langchain4j.watsonx.tokenizer2.api-key=${WATSONX_API_KEY}
quarkus.langchain4j.watsonx.tokenizer2.chat-model.model-id=meta-llama/llama-2-70b-chat

```

Everything works fine! From my point of view we can close this issue, but I don't know if you want to wait for the next version.

**Closed** 2024-02-16 15:08 UTC
Labels: enhancement, area/model
