### ISSUE TITLE
Concurrent issue with InMemoryChatMemoryStore

### ISSUE THREAD

**Issue by andreadimaio** [quarkiverse/quarkus-langchain4j#331] opened 2024-02-27 08:08 UTC
I found a problem when I run two concurrent API calls due to the use of the `InMemoryChatMemoryStore` with the memory id `default` in the [AiServiceMethodImplementationSupport](https://github.com/quarkiverse/quarkus-langchain4j/blob/7dae65702297764444ff6f35ca082560e883b52e/core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java#L100) class.

```java
Object memoryId = memoryId(createInfo, methodArgs).orElse("default");
```

From my initial analysis, the problem occurs when two threads execute the code that goes [from line 114 to line 129](https://github.com/quarkiverse/quarkus-langchain4j/blob/7dae65702297764444ff6f35ca082560e883b52e/core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java#L114-L129).

```java
if (context.hasChatMemory()) {
    ChatMemory chatMemory = context.chatMemory(memoryId);
    if (systemMessage.isPresent()) {
        chatMemory.add(systemMessage.get());
    }
    chatMemory.add(userMessage);
}

List<ChatMessage> messages;
if (context.hasChatMemory()) {
    messages = context.chatMemory(memoryId).messages();
} else {
    messages = new ArrayList<>();
    systemMessage.ifPresent(messages::add);
    messages.add(userMessage);
}
```

Using the same memory id (`default`) can lead to anomalous behavior in ChatMessage list objects, like the one I show you below.
I have an interface called `WatsonxService` annotated with `@RegisterAiService`:

```java
@SystemMessage("You are a poet")
@UserMessage("Write a poem of 5 lines about {topic}")
public String poemSync(String topic);
```

This service is exposed as endpoint at `/poem`:

```java
@GET
@Path("/")
public String watsonxPoemSync(@QueryParam("el") String el) {
     return watsonxService.poemSync(el);              
}
```

Now, when I run two curl commands in parallel
```
> curl http://localhost:8080/poem?el=dog
> curl http://localhost:8080/poem?el=cat
```
These are the results from the request logs:

```
2024-02-27 08:55:08,431 INFO  [io.qua.lan.wat.cli.WatsonxRestApi$WatsonClientLogger] (vert.x-eventloop-thread-3) Request:
- method: POST
- url: https://us-south.ml.cloud.ibm.com/ml/v1-beta/generation/text?version=2023-05-29
- headers: [Accept: application/json], [Authorization: Bearer eyJr...NiJ9], [Content-Type: application/json], [User-Agent: Resteasy Reactive Client], [content-length: 258]
- body: {"model_id":"meta-llama/llama-2-70b-chat","project_id":"23d...4fc","input":"You are a poet\n\nWrite a poem of 5 lines about dog\n","parameters":{"decoding_method":"greedy","min_new_tokens":0,"max_new_tokens":200,"temperature":1.0}}
```
```
2024-02-27 08:55:08,776 INFO  [io.qua.lan.wat.cli.WatsonxRestApi$WatsonClientLogger] (vert.x-eventloop-thread-2) Request:
- method: POST
- url: https://us-south.ml.cloud.ibm.com/ml/v1-beta/generation/text?version=2023-05-29
- headers: [Accept: application/json], [Authorization: Bearer eyJr...NiJ9], [Content-Type: application/json], [User-Agent: Resteasy Reactive Client], [content-length: 293]
- body: {"model_id":"meta-llama/llama-2-70b-chat","project_id":"23d...4fc","input":"You are a poet\n\nWrite a poem of 5 lines about dog\nWrite a poem of 5 lines about cat\n","parameters":{"decoding_method":"greedy","min_new_tokens":0,"max_new_tokens":200,"temperature":1.0}}
```
We need to focus our attention on the `input` field of the body requests.
In the first request, the `input` field contains what I expect:
```
You are a poet\n\nWrite a poem of 5 lines about dog\n
```
but in the second, the result is:
```
You are a poet\n\nWrite a poem of 5 lines about dog\nWrite a poem of 5 lines about cat\n
```
As you can see, the `@UserMessage` in the second request does not contain the correct value, and from my point of view this happens when the messages are taken from the `context.chatMemory(...)`.
If you wanna try it yourself: `git clone https://github.com/andreadimaio/quarkuslangchain4jtest.git`

**Comment by andreadimaio** [comment] 2024-02-27 08:10
Looking at the code [SyntheticBeanBuildItem](https://github.com/quarkiverse/quarkus-langchain4j/blob/fa7952e4f98298d4e03347ffae57cf70890dc461/core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java#L356-L367) uses `Dependent` scope, so in my scenario the `@RequestScoped` should be used, is this correct? At this point the `ChatMemoryProvider` should be created for each request and the problem should only be present when I use an `@ApplicationScoped`.

Something I'm missing... 😕

**Comment by geoand** [comment] 2024-02-27 08:13
This is to be expected, no?

I mean if you use the default object for a memory ID and make two calls at exactly the same time, you are going to be referencing the same chat memory.

**Comment by andreadimaio** [comment] 2024-02-27 08:17
No, because if I run the two rest api calls separately, the result is: `You are a poet\and Write a poem of 5 lines about dog\n` for two times and this is the expected behavior. If I'm using a memory the result should be a `SystemMessage - UserMessage - AiMessage - UserMessage`

**Comment by andreadimaio** [comment] 2024-02-27 08:20
That's the way I think about it 😃

**Comment by geoand** [comment] 2024-02-27 08:30
I agree, that would be the expected behavior in isolation, but when you haven't take care to create such isolation, it is inevitable that messages will be interleaved. 

Perhaps we should have some strongly worded warning when this happens...

**Comment by andreadimaio** [comment] 2024-02-27 08:37
I'm not sure that warning is enough. The framework makes this memory feature available, so the framework itself should take care of this problem, because unexpected problems could arise due to this behavior. Wouldn't it be a good idea at this point not to have any type of memory and if I need it, enable it explicitly?

**Comment by geoand** [comment] 2024-02-27 08:41
> Wouldn't it be a good idea at this point not to have any type of memory and if I need it, enable it explicitly?

In theory yes, in practice not really because it will really complicate demos...

**Comment by geoand** [comment] 2024-02-29 06:34
Same underlying cause :)

**Comment by geoand** [comment] 2024-02-29 09:01
I have something else in mind I would like to try

**Comment by andreadimaio** [comment] 2024-02-29 09:09
Cool, from my point of view maybe the problem can be limited to replacing the `default` memory id with a prefix obtained from the combination of the class and method name, because from my point of view the scope of the ChatMemory should not be above the `@SystemMessage`.
```java
@RegisterAiService
@SystemMessage("You are a funny boy")
public interface LLMService {
    
    @SystemMessage("You are a poet")
    @UserMessage("Write a poem of 5 lines about {topic}")
    public String poem(String topic); // memoryId = LLMServicepoem

    @SystemMessage("You are a calculator")
    @UserMessage("Execute {firstNumber} + {secondNumber}")
    public String calculator(int firstNumber, int secondNumber); // memoryId = LLMServicecalculator

    @UserMessage("Write 5 lines about you")
    public String tellMeSomethingAboutYou(); // memoryId = LLMService

    @UserMessage("Write a joke of maximum 5 lines")
    public String writeAJoke(@MemoryId memid); // memoryId = LLMService + \{memid}
}
```

But I'm curious about what you have in mind.

**Comment by geoand** [comment] 2024-02-29 09:25
Can you give https://github.com/quarkiverse/quarkus-langchain4j/pull/339 a try please?

**Comment by andreadimaio** [comment] 2024-02-29 10:30
> Can you give #339 a try please?

That's not enough, because `ChatMemory` now has a `@RequestScope` context, but `ChatMemoryStore` does not.

<img width="283" alt="image" src="https://github.com/quarkiverse/quarkus-langchain4j/assets/85737936/b89284fe-5e00-49dd-97fc-583c38bb8f70">

**Comment by andreadimaio** [comment] 2024-02-29 10:38
I don't think I fully understood the change you made. In any case, the problem still exists.

**Comment by geoand** [comment] 2024-02-29 10:47
Ah, it seems like my assumption about what `RequestContext` represents was wrong, let me fix that

**Comment by geoand** [comment] 2024-02-29 10:58
It should work now, can you check again please?

**Comment by geoand** [comment] 2024-02-29 11:08
Exactly :)

**Comment by andreadimaio** [comment] 2024-02-29 11:29
> `requestContext.isActive()` is true when there is an ongoing request being served (like an HTTP request). The scope of the AiService itself has no effect on the result of this call

Exactly, this means that if you expose an LLM service via an HTTP request, you will never have memory. It's just a note :)

**Comment by geoand** [comment] 2024-02-29 11:32
> Exactly, this means that if you expose an LLM service via an HTTP request, you will never have memory. It's just a note :)

I don't understand how you come to that conclusion :)

**Comment by andreadimaio** [comment] 2024-02-29 11:42
This is what happened **before** your commit
```java
@RegisterAiService
@ApplicationScoped
public interface LLMService {
    
    @SystemMessage("You are a poet")
    @UserMessage("Write a poem of 5 lines about {topic}")
    public String poem(String topic);
}
```

First request result:
```
2024-02-29 12:37:43,010 INFO  [io.qua.lan.bam.BamRestApi$BamClientLogger] (vert.x-eventloop-thread-1) Request:
- method: POST
- url: https://bam-api.res.ibm.com/v2/text/chat?version=2024-02-20
- headers: [Accept: application/json], [Authorization: ], [Content-Type: application/json], [User-Agent: Resteasy Reactive Client], [content-length: 262]
- body: {"model_id":"meta-llama/llama-2-70b-chat","messages":[{"role":"system","content":"You are a poet"},{"role":"user","content":"Write a poem of 5 lines about dog"}],"parameters":{"decoding_method":"greedy","min_new_tokens":0,"max_new_tokens":200,"temperature":1.0}}
```

Second request result:
```
2024-02-29 12:37:53,800 INFO  [io.qua.lan.bam.BamRestApi$BamClientLogger] (vert.x-eventloop-thread-0) Request:
- method: POST
- url: https://bam-api.res.ibm.com/v2/text/chat?version=2024-02-20
- headers: [Accept: application/json], [Authorization: ], [Content-Type: application/json], [User-Agent: Resteasy Reactive Client], [content-length: 536]
- body: {"model_id":"meta-llama/llama-2-70b-chat","messages":[{"role":"system","content":"You are a poet"},{"role":"user","content":"Write a poem of 5 lines about dog"},{"role":"assistant","content":"  A furry friend so loyal and true,\nTail wagging, eyes shining bright,\nBringing joy and comfort to you,\nA companion through day and night,\nA love that will never take flight."},{"role":"user","content":"Write a poem of 5 lines about dog"}],"parameters":{"decoding_method":"greedy","min_new_tokens":0,"max_new_tokens":200,"temperature":1.0}}
```

As you can see there is an assistant message in the body response for the second request.

----------------------------------------

Now with your last commit the result is

First request:
```
2024-02-29 12:41:33,615 INFO  [io.qua.lan.bam.BamRestApi$BamClientLogger] (vert.x-eventloop-thread-1) Request:
- method: POST
- url: https://bam-api.res.ibm.com/v2/text/chat?version=2024-02-20
- headers: [Accept: application/json], [Authorization: ], [Content-Type: application/json], [User-Agent: Resteasy Reactive Client], [content-length: 262]
- body: {"model_id":"meta-llama/llama-2-70b-chat","messages":[{"role":"system","content":"You are a poet"},{"role":"user","content":"Write a poem of 5 lines about dog"}],"parameters":{"decoding_method":"greedy","min_new_tokens":0,"max_new_tokens":200,"temperature":1.0}}
```

Second request:
```
2024-02-29 12:41:37,233 INFO  [io.qua.lan.bam.BamRestApi$BamClientLogger] (vert.x-eventloop-thread-0) Request:
- method: POST
- url: https://bam-api.res.ibm.com/v2/text/chat?version=2024-02-20
- headers: [Accept: application/json], [Authorization: ], [Content-Type: application/json], [User-Agent: Resteasy Reactive Client], [content-length: 262]
- body: {"model_id":"meta-llama/llama-2-70b-chat","messages":[{"role":"system","content":"You are a poet"},{"role":"user","content":"Write a poem of 5 lines about dog"}],"parameters":{"decoding_method":"greedy","min_new_tokens":0,"max_new_tokens":200,"temperature":1.0}}
```

Maybe we are not on the same page because i'm using the word memory and not history?

**Comment by geoand** [comment] 2024-02-29 12:07
Ah okay, now I see what you mean. 

So indeed what changes now is that when no memoryId is used, an `@ApplicationScoped` or `@Singleton` AiService will no longer carry the memory from request to the next.
I would say that is much safer than the previous behavior, although I would definitely question the use of either of those two scopes.

**Comment by andreadimaio** [comment] 2024-02-29 12:16
> So indeed what changes now is that when no memoryId is used, an `@ApplicationScoped` or `@Singleton` AiService will no longer carry the memory from request to the next.

Yep!

> I would say that is much safer than the previous behavior, although I would definitely question the use of either of those two scopes.

I agree!

----------------------------

I pointed out this behavior to you because the documentation of `quarkus-langchain4j` says about using `@Tools`:
```
Why I When using tools, you need a memory of at least 3 messages to cover the tools interaction.
```
I don't have the opportunity to test the `@Tools`, but if I remember correctly, there are some JUnit tests on this topic.

**Comment by geoand** [comment] 2024-02-29 12:18
We should update that documentation because it's no longer true as we enable in memory chat history by default

**Comment by andreadimaio** [comment] 2024-02-29 12:20
Ok perfect, so from my point of view this PR can be closed.

**Closed** 2024-02-29 13:07 UTC
